title: "Gintare-Maria Balciute"
author: "G. M. Balciute"
description: "gintare.maria@proton.me"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: Contact to buy, url: "mailto:gintare.maria@proton.me"}
  - {title: About me, file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Email, icon: envelope, url: "mailto:gintare.maria@proton.me"}
  - {title: Instagram, icon: instagram, url: "https://instagram.com/gmbalc"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
